hashnote/urls.py
from django.conf.urls import patterns, include, url

#from hashnote.views import NoteCreateView

urlpatterns = patterns('hashnote.views',

    url(r'^/?$', 
        'note_list',
        name='home'),

    #url(r'^tag/(?P<tag>[0-9A-Za-z-]+)/?$', 
    #    'note_list',
    #    name='tag'),

    #url(r'^add/?$', 
    #    NoteCreateView.as_view(), 
    #    name='create'),

    url(r'^note/?$', 
        'notes_api',
        name='notes-api'),
)

interview/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    
    url(r'^', 
        include('hashnote.urls', 
            namespace='hashnote', 
            app_name='hashnote')),

)

hashnote/models.py
import re

from django.db import models
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save

from tagging.fields import TagField

class Note(models.Model):
    """
    """

    text            = models.TextField()
    date_created    = models.DateTimeField(auto_now_add=True)
    tags            = TagField()
    shortlist       = models.BooleanField()

    class Meta:
        ordering = ['date_created']

    def get_absolute_url(self):
        return reverse('hashnote:home')

    def to_dict(self):
        return {
                'id': self.id,
                'text': self.text,
                'tags': self.tags.split(),
                'date_created': self.date_created.isoformat()
                }

@receiver(pre_save, sender=Note)
def note_tag_handler(sender, instance, **kwargs):

    tags = re.findall('#(\w+)', instance.text)
    instance.tags = ' '.join(tags)

hashnote/forms.py
from django import forms

from hashnote.models import Note

class NoteForm(forms.ModelForm):
    """
    """

    text = forms.CharField(
            widget=forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'New Note'
                    }), 
            label='New Note')

    class Meta:
        model = Note
        exclude = ['tags']

hashnote/views.py
import json

from django.shortcuts import render_to_response
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt

from hashnote.models import Note
from hashnote.forms import NoteForm

@csrf_exempt
def notes_api(request):
    """
    """

    data = []

    if request.method == 'GET':

        notes = Note.objects.all()

        for note in notes:
            data.append(note.to_dict())

    elif request.method == 'POST':
    
        shortlist = request.POST.get('shortlist') == 'on'

        note = Note.objects.create(
                text=request.POST.get('text'),
                shortlist=shortlist
                )

        data.append(note.to_dict())
    
    return HttpResponse(
            json.dumps(data), 
            mimetype='application/json')


def note_list(request, tag=None):
    """
    """

    notes = Note.objects.all()
    shortlist_notes = notes.filter(shortlist=True)

    form = NoteForm()

    if tag:
        notes = notes.filter(tags__contains=tag)

    return render_to_response('hashnote/note_list.html', locals())

hashnote/templates/hashnote/note_list.html
{% extends "base.html" %}
{% load tagging_tags %}

{% block extra-js %}

    <script>

        // Create list from json data
        function buildNoteList(data) {

            var noteTemplate, recentNotes;

            noteTemplate = $('#templates .note');
            recentNotes = $('#recent-notes');

            $.each(data, function() {
                var noteLi = noteTemplate.clone();
                noteLi.find('.note-text').text(this.text);
                noteLi.find('.note-date').text(this.date_created);
                noteLi.addClass(this.tags.join(' '));
                recentNotes.prepend(noteLi); 
            });
        };

        // Show loading message 
        $(document).ajaxStart(function() {
            $('body').addClass('loading');
        }).ajaxStop(function() {
            $('body').removeClass('loading');
        });

        $(document).ready(function() {

            // Get all notes on initial page load
            $.ajax({
                url: "{% url 'hashnote:notes-api' %}",
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    $('#recent-notes').empty();
                    buildNoteList(data);
               }
            });

            // Filter by tag
            $('a.tag').click(function(e) {

                e.preventDefault();
                
                var tag = $(this).text();

                $('.note').hide().filter(function() {
                    return $(this).hasClass(tag);
                }).fadeIn('fast');
            });

            // Reset tag filter
            $('#reset-tags').click(function(e) {
                e.preventDefault();
                $('.note').show();
            });

            // Submit form
            $('form').submit(function(e) {

                e.preventDefault();

                var thisForm = $(this);

                var formData = {
                    text: thisForm.find('[name=text]').val(),
                    shortlist: thisForm.find('[name=shortlist]').val()
                };

                $.ajax({
                    url: "{% url 'hashnote:notes-api' %}",
                    type: 'POST',
                    data: formData,
                    dataType: 'json',
                    success: function(data) {
                        buildNoteList(data);
                    }
                });
            });

            // Submit shortlist note
            $('a.shortlist-note').click(function(e) {

                e.preventDefault();

                var formData = {
                    text: $(this).text()
                };

                $.ajax({
                    url: "{% url 'hashnote:notes-api' %}",
                    type: 'POST',
                    data: formData,
                    dataType: 'json',
                    success: function(data) {
                        buildNoteList(data);
                    }
                });
            });

        });
    </script>

{% endblock %}

{% block extra-css %}

    <style>

        li {
            margin-bottom: 1em;
        }

        li.note {
            padding: 1em;
            background: #f8f8f8;
            border: 1px solid #eee;
        }

        #templates, #loading {
            display: none;
        }

        body.loading #loading {
            display: block;
        }

        #loading {
            position: fixed;
            top: 0;
            left: 47%;
            right: 47%;
            padding: 5px;
            background: #eee;
            text-align: center;
        }

    </style>

{% endblock %}

{% block content %}

    <h1>HashNote</h1>

    <div class="row">
        <form role="form" class="note-form form-inline" method="post">
            {% csrf_token %}
            <div class="form-group">
                {{ form }}
            </div>
            <input class="btn btn-default" type="submit" />
        </form>
    </div>

    <div class="row">

        <div class="col-md-8">
            <h4>Recent Notes</h4>
            <ul id="recent-notes" class="list-unstyled"></ul>
        </div>

        <div class="col-md-4">

            <h4>Pre-made Notes</h4>

            <ul class="list-unstyled">
                {% for note in shortlist_notes %}
                <li>
                    <a class="shortlist-note btn btn-small" href="#">{{ note.text }}</a>
                </li>
                {% endfor %}
            </ul>

            <h4>Recent Tags</h4>

            {% tags_for_model hashnote.Note as all_tags %}
            <ul class="list-unstyled">

                {% for tag in all_tags %}
                <li>
                    <a class="tag btn btn-small" 
                        href="#">{{ tag }}</a>
                    ({{ tag.items.count }})
                </li>
                {% endfor %}

                {% if tag %}
                <li>
                    <a href="#" id="reset-tags">Reset Filter</a>
                </li>
                {% endif %}

            </ul>
        </div>

    </div>

    <div id="templates">
        <li class="note">
            <span class="note-text"></span>
            <small class="pull-right note-date"></small>
        </li>
    </div>

{% endblock %}

interview/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
	<head>
		<title>HashNotes</title>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
    
        {% block extra-css %}
        {% endblock %}

	</head>

	{% autoescape off %}
	<body>

        <div id="loading">Loading&hellip;</div>

        <div class="container">
            {% block content %}

            {% endblock %}
        </div>

	</body>
	{% endautoescape %}

    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

    {% block extra-js %}
    
    {% endblock %}

</html>